version: '3.4'

services:
    iitdappwebsite:
        build: .
        image: "${REGISTRY_NAME}devclubiitd/iitdappwebsite:1.0"
        ports:
            - 80
        restart: 'unless-stopped'
        networks:
            - "internal"
            - "reverseproxy"
        environment:
            - VIRTUAL_HOST

networks:
    reverseproxy:
        external:
            name: "reverseproxy"
    internal:
