/* eslint-disable react/prefer-stateless-function */
import React from 'react';
import { Responsive, WidthProvider } from 'react-grid-layout';
import NewsCard from './newsCard';
import news from './shared/news';

const ResponsiveGridLayout = WidthProvider(Responsive);

class News extends React.Component {
    render() {
        const layoutLg = [
            {
                i: '0',
                x: 0,
                y: 0,
                w: 1,
                h: 1.75,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '1',
                x: 1,
                y: 0,
                w: 1,
                h: 1.75,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '2',
                x: 0,
                y: 1.8,
                w: 1,
                h: 1.75,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '3',
                x: 1,
                y: 1.8,
                w: 1,
                h: 1.75,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '4',
                x: 0,
                y: 3.6,
                w: 1,
                h: 1.75,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '5',
                x: 1,
                y: 3.6,
                w: 1,
                h: 1.75,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '6',
                x: 0,
                y: 5.4,
                w: 1,
                h: 1.75,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '7',
                x: 1,
                y: 3,
                w: 5.4,
                h: 1.75,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '8',
                x: 0,
                y: 7.2,
                w: 1,
                h: 1.75,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '9',
                x: 1,
                y: 7.2,
                w: 1,
                h: 1.75,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '10',
                x: 0,
                y: 9,
                w: 1,
                h: 1.75,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '11',
                x: 1,
                y: 9,
                w: 1,
                h: 1.75,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '12',
                x: 0,
                y: 10.8,
                w: 1,
                h: 1.75,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
        ];
        const layoutXs = [
            {
                i: '0',
                x: 0,
                y: 0,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
            },
            {
                i: '1',
                x: 1,
                y: 1,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '2',
                x: 0,
                y: 0,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '3',
                x: 1,
                y: 0,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '4',
                x: 0,
                y: 0,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '5',
                x: 1,
                y: 0,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '6',
                x: 0,
                y: 3,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '7',
                x: 1,
                y: 3,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '8',
                x: 0,
                y: 3,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '9',
                x: 1,
                y: 3,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '10',
                x: 0,
                y: 3,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '11',
                x: 8,
                y: 3,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '12',
                x: 1,
                y: 3,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
        ];
        const layoutXxs = [
            {
                i: '0',
                x: 0,
                y: 0,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
            },
            {
                i: '1',
                x: 0,
                y: 1,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '2',
                x: 0,
                y: 0,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '3',
                x: 6,
                y: 0,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '4',
                x: 8,
                y: 0,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '5',
                x: 0,
                y: 0,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '6',
                x: 0,
                y: 3,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '7',
                x: 0,
                y: 3,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '8',
                x: 0,
                y: 3,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '9',
                x: 0,
                y: 3,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '10',
                x: 0,
                y: 3,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '11',
                x: 0,
                y: 3,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
            {
                i: '12',
                x: 0,
                y: 3,
                w: 1,
                h: 2.8,
                isResizable: false,
                useCSSTransforms: true,
                verticalCompact: true,
                isDraggable: false,
            },
        ];
        const layouts = { lg: layoutLg, xxs: layoutXxs, xs: layoutXs };
        const newsRoll = news.map((newsObj) => {
            return (
                <div key={newsObj.id} className="newsGrid">
                    <NewsCard newsObj={newsObj} />
                </div>
            );
        });

        return (
            <ResponsiveGridLayout
                className="layout"
                layouts={layouts}
                breakpoints={{
                    lg: 1200,
                    md: 996,
                    md2: 768,
                    sm: 580,
                    xs: 396,
                    xxs: 0,
                }}
                cols={{ lg: 2, md: 1, md2: 1, sm: 1, xs: 1, xxs: 1 }}
                horizontalCompact
            >
                {newsRoll}
            </ResponsiveGridLayout>
        );
    }
}

export default News;
